apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: public-endpoint-route
  namespace: public-endpoint
spec:
  parentRefs:
    - name: main-gateway
      namespace: envoy-gateway-system
  hostnames:
    - "*.e.httptoolk.it"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: public-endpoint
          port: 80