apiVersion: v1
kind: Service
metadata:
  name: public-endpoint
  namespace: public-endpoint
spec:
  selector:
    app: public-endpoint
  ports:
    - name: admin-port
      protocol: TCP
      port: 4000
      targetPort: 4000
    - name: endpoints-port
      protocol: TCP
      port: 80
      targetPort: 4040